### ISSUE TITLE
Remove 'Node' from the names of the schemas

### ISSUE THREAD

**Issue by antoniogarrote** [api-modeling/metadata#9]
The name of the schema is the default label to identify it.

Sometimes we have used 'Node' in the past, when looking at those schemas as nodes in the dialect instance AST, but from the data model point of view we prefer to use a more semantic label.

We should remove the 'Node' termination from all the schemas in the dialects:

ModuleNode -> Module

**Comment by mattdfuchs** [comment]
Will do, however I am not happy about the shape and the thing it shapes having the same name.
